let celular1={
    marca:'samsung',
    modelo:'galaxy S23',
    armazenamento:'512Gb',
    ram:'12Gb',
    processador:'Qualcomm Snapdragon',
    tipoTela:'Ips',
    cor:'branco',
    bateria:'5.000mAh',
    preco:'3000',
}

let celular2={
    marca:'Motorola',
    modelo:'Edge',
    armazenamento:'256GB',
    ram:'6.0GB',
    processador:'Qualcomm snapdragon 765',
    tipoTela:'Ltpo AMOled',
    cor:'vermelho',
    bateria:'E6 plus',
    preco:'1900',
}

let celular3={
    marca:'samsung',
    modelo:'Galaxy S23',
    armazenamento:'512gb',
    ram:'12gb'
    processador:'snapragon',
    tipoTela:'ips',
    cor:'azul',
    bateria:'500Mah',
    preco:'2400',
}

let celular4={
    marca:''
    modelo:''
    armazenamento:''
    ram:''
    processador:''
    tipoTela:''
    cor:''
    bateria:''
    preco:''
}

let celular5={
    marca:''
    modelo:''
    armazenamento:''
    ram:''
    processador:''
    tipoTela:''
    cor:''
    bateria:''
    preco:''
